import {MigrationInterface, QueryRunner} from "typeorm";

export class baseMigration1666382991146 implements MigrationInterface {
    name = 'baseMigration1666382991146'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "offer_videos" ("id" SERIAL NOT NULL, "video" character varying NOT NULL, "offerId" integer NOT NULL, CONSTRAINT "PK_a2fd07a1261a40ad82f20f1f0a9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "company_images" ("id" SERIAL NOT NULL, "image" character varying, "image_key" character varying, "companyId" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_9bb753e6a339324894c38f525c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "country_images" ("id" SERIAL NOT NULL, "image" character varying, "image_key" character varying, "countryId" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_3489bfd71d40238f438b4a70062" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "countries" ("id" SERIAL NOT NULL, "name_en" character varying NOT NULL, "name_ar" character varying NOT NULL, "code" character varying NOT NULL, "status" boolean NOT NULL DEFAULT true, "flag" character varying NOT NULL, "flag_key" character varying, CONSTRAINT "UQ_ec136751aedebfedc5dcb1a65ac" UNIQUE ("name_en"), CONSTRAINT "UQ_4e409b241a4a30c5e518b1d406c" UNIQUE ("name_ar"), CONSTRAINT "PK_b2d7006793e8697ab3ae2deff18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "directory" ("id" SERIAL NOT NULL, "pdf" character varying NOT NULL, "pdf_key" character varying NOT NULL, "year" character varying, "cityId" integer NOT NULL, CONSTRAINT "UQ_6bc90a5514b6496b34723c78384" UNIQUE ("cityId"), CONSTRAINT "PK_3031979b800d63fadf8ce7e33b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."request-directory_status_enum" AS ENUM('pending', 'accepted', 'rejected')`);
        await queryRunner.query(`CREATE TYPE "public"."request-directory_type_enum" AS ENUM('paper', 'pdf', 'both')`);
        await queryRunner.query(`CREATE TABLE "request-directory" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "status" "public"."request-directory_status_enum" NOT NULL DEFAULT 'pending', "type" "public"."request-directory_type_enum" NOT NULL, "company_name" character varying NOT NULL, "email" character varying NOT NULL, "phone" character varying NOT NULL, "pdf" character varying NOT NULL, "cityId" integer NOT NULL, "userId" integer NOT NULL, CONSTRAINT "PK_79ed77db2923f55825a838ce0ca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "city" ("id" SERIAL NOT NULL, "name_en" character varying NOT NULL, "name_ar" character varying NOT NULL, "image" character varying, "image_key" character varying, "institution_name" character varying, "status" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "countryId" integer, CONSTRAINT "UQ_806d8437e13ce000abe84e3e808" UNIQUE ("name_en"), CONSTRAINT "UQ_6184966b86c8ff8ad854b29400e" UNIQUE ("name_ar"), CONSTRAINT "PK_b222f51ce26f7e5ca86944a6739" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "company_phones" ("id" SERIAL NOT NULL, "phone" character varying NOT NULL, "companyId" integer NOT NULL, CONSTRAINT "PK_80de2320e1384df4e090c8f2e5c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "company_videos" ("id" SERIAL NOT NULL, "video" character varying NOT NULL, "companyId" integer NOT NULL, CONSTRAINT "PK_794097e6d1193144c87d2acee59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "company" ("id" SERIAL NOT NULL, "name_en" character varying NOT NULL, "name_ar" character varying NOT NULL, "email" character varying NOT NULL, "standard_phone" character varying NOT NULL, "website" character varying NOT NULL, "post_code" character varying, "verified" boolean NOT NULL DEFAULT false, "degree" character varying, "logo" character varying, "logo_key" character varying, "banner" character varying, "banner_key" character varying, "latitude" character varying, "longitude" character varying, "facebook" character varying, "twitter" character varying, "linkedin" character varying, "whatsapp" character varying, "snapchat" character varying, "instagram" character varying, "youtube_video" character varying, "agent_name" character varying, "paid_offers_status" boolean NOT NULL DEFAULT false, "hotline" character varying, "building_no" character varying, "street_ar" character varying, "street_en" character varying, "description_en" character varying, "description_ar" character varying, "district_en" character varying, "district_ar" character varying, "commercial_reg" character varying, "views" integer NOT NULL DEFAULT '0', "userId" integer, "countryId" integer, "cityId" integer, "status" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_056f7854a7afdba7cbd6d45fc20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" SERIAL NOT NULL, "name_en" character varying NOT NULL, "name_ar" character varying NOT NULL, "status" boolean NOT NULL DEFAULT true, "views" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "offer_images" ("id" SERIAL NOT NULL, "image" character varying, "image_key" character varying, "offerId" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_4945bec7ed3216934b70e3f213c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."offer_sale_type_enum" AS ENUM('PERCENTAGE', 'AMOUNT')`);
        await queryRunner.query(`CREATE TABLE "offer" ("id" SERIAL NOT NULL, "name_en" character varying NOT NULL, "name_ar" character varying NOT NULL, "address_en" character varying, "address_ar" character varying, "description_en" character varying, "description_ar" character varying, "on_sale" boolean NOT NULL DEFAULT false, "sale_amount" integer NOT NULL DEFAULT '0', "sale_type" "public"."offer_sale_type_enum" NOT NULL DEFAULT 'PERCENTAGE', "paid" boolean NOT NULL DEFAULT false, "status" boolean NOT NULL DEFAULT true, "userId" integer NOT NULL, "countryId" integer NOT NULL, "cityId" integer NOT NULL, "companyId" integer NOT NULL, "views" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "endAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_57c6ae1abe49201919ef68de900" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum" AS ENUM('USER', 'ADMIN', 'SUPERVISOR', 'EDITOR')`);
        await queryRunner.query(`CREATE TYPE "public"."user_default_language_enum" AS ENUM('en', 'ar')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "role" "public"."user_role_enum" NOT NULL DEFAULT 'USER', "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "default_language" "public"."user_default_language_enum" NOT NULL DEFAULT 'ar', "status" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "branch" ("id" SERIAL NOT NULL, "name_en" character varying NOT NULL, "name_ar" character varying NOT NULL, "address_ar" character varying NOT NULL, "address_en" character varying NOT NULL, "phone" character varying NOT NULL, "description_ar" character varying NOT NULL, "description_en" character varying NOT NULL, "link" character varying, "userId" integer NOT NULL, "companyId" integer NOT NULL, "userIdId" integer, "companyIdId" integer, CONSTRAINT "PK_2e39f426e2faefdaa93c5961976" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "privacy-policy" ("id" SERIAL NOT NULL, "page" character varying NOT NULL, "slug" character varying NOT NULL, "title" character varying NOT NULL, "content" character varying NOT NULL, CONSTRAINT "PK_ce6c69ac8a4aee173949db3757c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "setting" ("id" SERIAL NOT NULL, "setting" character varying NOT NULL DEFAULT 'done', "title_en" character varying NOT NULL, "title_ar" character varying NOT NULL, "description_en" character varying NOT NULL, "description_ar" character varying NOT NULL, "keywords" character varying NOT NULL, "facebook" character varying NOT NULL, "twitter" character varying NOT NULL, "instagram" character varying NOT NULL, "linkedin" character varying NOT NULL, "snapchat" character varying NOT NULL, "youtube" character varying NOT NULL, "logo" character varying NOT NULL, "logo_key" character varying, "phone" character varying NOT NULL, "email" character varying NOT NULL, "whatsapp" character varying NOT NULL, "address_en" character varying NOT NULL, "address_ar" character varying NOT NULL, "copyright_en" character varying NOT NULL, "copyright_ar" character varying NOT NULL, "location" character varying NOT NULL, "total_views" integer NOT NULL DEFAULT '0', "company_views" integer NOT NULL DEFAULT '0', "offer_views" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_9e2d4318b738187b6a32ac0d0cb" UNIQUE ("setting"), CONSTRAINT "PK_fcb21187dc6094e24a48f677bed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "testimonial" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "job" character varying NOT NULL, "rating" integer NOT NULL, "content" character varying NOT NULL DEFAULT true, "image" character varying NOT NULL, "image_key" character varying NOT NULL, CONSTRAINT "UQ_0ec11a58251285c68c7c4f3b583" UNIQUE ("name"), CONSTRAINT "PK_e1aee1c726db2d336480c69f7cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "favorite_companies" ("userId" integer NOT NULL, "companyId" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_e1b498aa48d2a79b6c0543295a5" PRIMARY KEY ("userId", "companyId"))`);
        await queryRunner.query(`CREATE TABLE "reset_password" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "token" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_888bab4800d3eeb1856af8e9fc7" UNIQUE ("token"), CONSTRAINT "PK_82bffbeb85c5b426956d004a8f5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "company_categories" ("companyId" integer NOT NULL, "categoriesId" integer NOT NULL, CONSTRAINT "PK_344cd650992b46539137bbef713" PRIMARY KEY ("companyId", "categoriesId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_57b50afbea3e46eea2765825cb" ON "company_categories" ("companyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a0c73e0e7c2783ad2867fb0cfb" ON "company_categories" ("categoriesId") `);
        await queryRunner.query(`CREATE TABLE "offer_categories" ("categoriesId" integer NOT NULL, "offerId" integer NOT NULL, CONSTRAINT "PK_44adba6a7f517f70d8ea1ef8663" PRIMARY KEY ("categoriesId", "offerId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_62e041cec8c590dfdced089f93" ON "offer_categories" ("categoriesId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7c3505ff98bc374f03bed21b79" ON "offer_categories" ("offerId") `);
        await queryRunner.query(`CREATE TABLE "user_companies" ("userId" integer NOT NULL, "companyId" integer NOT NULL, CONSTRAINT "PK_0b5b4fd1b21f221e3f91a438d93" PRIMARY KEY ("userId", "companyId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_295e2ec0606b47e50687ff46c3" ON "user_companies" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fbcec9c4908de8338081b5bfeb" ON "user_companies" ("companyId") `);
        await queryRunner.query(`CREATE TABLE "user_offers" ("userId" integer NOT NULL, "offerId" integer NOT NULL, CONSTRAINT "PK_a71270d4cdc4e0c5fa4f45a8d48" PRIMARY KEY ("userId", "offerId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8bcabd221862f7368ab3747eb8" ON "user_offers" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d54a136f7502f10a28c7599f10" ON "user_offers" ("offerId") `);
        await queryRunner.query(`ALTER TABLE "offer_videos" ADD CONSTRAINT "FK_dd4ca2e27edca21f7048fb60467" FOREIGN KEY ("offerId") REFERENCES "offer"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_images" ADD CONSTRAINT "FK_854a65ecc43305f9324044e76fd" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "country_images" ADD CONSTRAINT "FK_8ef91d5aad93d028f47bac12780" FOREIGN KEY ("countryId") REFERENCES "countries"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "directory" ADD CONSTRAINT "FK_6bc90a5514b6496b34723c78384" FOREIGN KEY ("cityId") REFERENCES "city"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "request-directory" ADD CONSTRAINT "FK_090ab1e96673d6c37478994d433" FOREIGN KEY ("cityId") REFERENCES "city"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "request-directory" ADD CONSTRAINT "FK_f58aebe930b28580a19d3489124" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "city" ADD CONSTRAINT "FK_990b8a57ab901cb812e2b52fcf0" FOREIGN KEY ("countryId") REFERENCES "countries"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_phones" ADD CONSTRAINT "FK_2db6e1b030700009b98b6d5b5d3" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_videos" ADD CONSTRAINT "FK_ca837606f19fd2bf7b134a4fd5e" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company" ADD CONSTRAINT "FK_c41a1d36702f2cd0403ce58d33a" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company" ADD CONSTRAINT "FK_9731df468316e5b1a689b906240" FOREIGN KEY ("countryId") REFERENCES "countries"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company" ADD CONSTRAINT "FK_d37b1b0cc9656c160b5464ac4f3" FOREIGN KEY ("cityId") REFERENCES "city"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offer_images" ADD CONSTRAINT "FK_05c54594b3b07e9aa25beaa238b" FOREIGN KEY ("offerId") REFERENCES "offer"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offer" ADD CONSTRAINT "FK_e8100751be1076656606ae045e3" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offer" ADD CONSTRAINT "FK_df41e88b8332908316b8a20fefe" FOREIGN KEY ("countryId") REFERENCES "countries"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offer" ADD CONSTRAINT "FK_c13b80d2ccf08e839c8712fcad1" FOREIGN KEY ("cityId") REFERENCES "city"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offer" ADD CONSTRAINT "FK_7e3791c6351f63eaf655522c700" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch" ADD CONSTRAINT "FK_3bb539d0be94f0e64f83cbc1f6a" FOREIGN KEY ("userIdId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branch" ADD CONSTRAINT "FK_2375023fff48ae785ae2a559240" FOREIGN KEY ("companyIdId") REFERENCES "company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_categories" ADD CONSTRAINT "FK_57b50afbea3e46eea2765825cb5" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "company_categories" ADD CONSTRAINT "FK_a0c73e0e7c2783ad2867fb0cfbe" FOREIGN KEY ("categoriesId") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offer_categories" ADD CONSTRAINT "FK_62e041cec8c590dfdced089f937" FOREIGN KEY ("categoriesId") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "offer_categories" ADD CONSTRAINT "FK_7c3505ff98bc374f03bed21b79d" FOREIGN KEY ("offerId") REFERENCES "offer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_companies" ADD CONSTRAINT "FK_295e2ec0606b47e50687ff46c34" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_companies" ADD CONSTRAINT "FK_fbcec9c4908de8338081b5bfeb0" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_offers" ADD CONSTRAINT "FK_8bcabd221862f7368ab3747eb87" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_offers" ADD CONSTRAINT "FK_d54a136f7502f10a28c7599f101" FOREIGN KEY ("offerId") REFERENCES "offer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_offers" DROP CONSTRAINT "FK_d54a136f7502f10a28c7599f101"`);
        await queryRunner.query(`ALTER TABLE "user_offers" DROP CONSTRAINT "FK_8bcabd221862f7368ab3747eb87"`);
        await queryRunner.query(`ALTER TABLE "user_companies" DROP CONSTRAINT "FK_fbcec9c4908de8338081b5bfeb0"`);
        await queryRunner.query(`ALTER TABLE "user_companies" DROP CONSTRAINT "FK_295e2ec0606b47e50687ff46c34"`);
        await queryRunner.query(`ALTER TABLE "offer_categories" DROP CONSTRAINT "FK_7c3505ff98bc374f03bed21b79d"`);
        await queryRunner.query(`ALTER TABLE "offer_categories" DROP CONSTRAINT "FK_62e041cec8c590dfdced089f937"`);
        await queryRunner.query(`ALTER TABLE "company_categories" DROP CONSTRAINT "FK_a0c73e0e7c2783ad2867fb0cfbe"`);
        await queryRunner.query(`ALTER TABLE "company_categories" DROP CONSTRAINT "FK_57b50afbea3e46eea2765825cb5"`);
        await queryRunner.query(`ALTER TABLE "branch" DROP CONSTRAINT "FK_2375023fff48ae785ae2a559240"`);
        await queryRunner.query(`ALTER TABLE "branch" DROP CONSTRAINT "FK_3bb539d0be94f0e64f83cbc1f6a"`);
        await queryRunner.query(`ALTER TABLE "offer" DROP CONSTRAINT "FK_7e3791c6351f63eaf655522c700"`);
        await queryRunner.query(`ALTER TABLE "offer" DROP CONSTRAINT "FK_c13b80d2ccf08e839c8712fcad1"`);
        await queryRunner.query(`ALTER TABLE "offer" DROP CONSTRAINT "FK_df41e88b8332908316b8a20fefe"`);
        await queryRunner.query(`ALTER TABLE "offer" DROP CONSTRAINT "FK_e8100751be1076656606ae045e3"`);
        await queryRunner.query(`ALTER TABLE "offer_images" DROP CONSTRAINT "FK_05c54594b3b07e9aa25beaa238b"`);
        await queryRunner.query(`ALTER TABLE "company" DROP CONSTRAINT "FK_d37b1b0cc9656c160b5464ac4f3"`);
        await queryRunner.query(`ALTER TABLE "company" DROP CONSTRAINT "FK_9731df468316e5b1a689b906240"`);
        await queryRunner.query(`ALTER TABLE "company" DROP CONSTRAINT "FK_c41a1d36702f2cd0403ce58d33a"`);
        await queryRunner.query(`ALTER TABLE "company_videos" DROP CONSTRAINT "FK_ca837606f19fd2bf7b134a4fd5e"`);
        await queryRunner.query(`ALTER TABLE "company_phones" DROP CONSTRAINT "FK_2db6e1b030700009b98b6d5b5d3"`);
        await queryRunner.query(`ALTER TABLE "city" DROP CONSTRAINT "FK_990b8a57ab901cb812e2b52fcf0"`);
        await queryRunner.query(`ALTER TABLE "request-directory" DROP CONSTRAINT "FK_f58aebe930b28580a19d3489124"`);
        await queryRunner.query(`ALTER TABLE "request-directory" DROP CONSTRAINT "FK_090ab1e96673d6c37478994d433"`);
        await queryRunner.query(`ALTER TABLE "directory" DROP CONSTRAINT "FK_6bc90a5514b6496b34723c78384"`);
        await queryRunner.query(`ALTER TABLE "country_images" DROP CONSTRAINT "FK_8ef91d5aad93d028f47bac12780"`);
        await queryRunner.query(`ALTER TABLE "company_images" DROP CONSTRAINT "FK_854a65ecc43305f9324044e76fd"`);
        await queryRunner.query(`ALTER TABLE "offer_videos" DROP CONSTRAINT "FK_dd4ca2e27edca21f7048fb60467"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d54a136f7502f10a28c7599f10"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8bcabd221862f7368ab3747eb8"`);
        await queryRunner.query(`DROP TABLE "user_offers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fbcec9c4908de8338081b5bfeb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_295e2ec0606b47e50687ff46c3"`);
        await queryRunner.query(`DROP TABLE "user_companies"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7c3505ff98bc374f03bed21b79"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_62e041cec8c590dfdced089f93"`);
        await queryRunner.query(`DROP TABLE "offer_categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a0c73e0e7c2783ad2867fb0cfb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_57b50afbea3e46eea2765825cb"`);
        await queryRunner.query(`DROP TABLE "company_categories"`);
        await queryRunner.query(`DROP TABLE "reset_password"`);
        await queryRunner.query(`DROP TABLE "favorite_companies"`);
        await queryRunner.query(`DROP TABLE "testimonial"`);
        await queryRunner.query(`DROP TABLE "setting"`);
        await queryRunner.query(`DROP TABLE "privacy-policy"`);
        await queryRunner.query(`DROP TABLE "branch"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_default_language_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum"`);
        await queryRunner.query(`DROP TABLE "offer"`);
        await queryRunner.query(`DROP TYPE "public"."offer_sale_type_enum"`);
        await queryRunner.query(`DROP TABLE "offer_images"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "company"`);
        await queryRunner.query(`DROP TABLE "company_videos"`);
        await queryRunner.query(`DROP TABLE "company_phones"`);
        await queryRunner.query(`DROP TABLE "city"`);
        await queryRunner.query(`DROP TABLE "request-directory"`);
        await queryRunner.query(`DROP TYPE "public"."request-directory_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."request-directory_status_enum"`);
        await queryRunner.query(`DROP TABLE "directory"`);
        await queryRunner.query(`DROP TABLE "countries"`);
        await queryRunner.query(`DROP TABLE "country_images"`);
        await queryRunner.query(`DROP TABLE "company_images"`);
        await queryRunner.query(`DROP TABLE "offer_videos"`);
    }

}
